version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - docker/web/.env
    entrypoint: /entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - "8045:8080"
    networks:
      - separated_network
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    networks:
      - separated_network

volumes:
  postgres_data:

networks:
  separated_network:
