version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - docker/web/.env
    entrypoint: /entrypoint.sh
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8045:8000"
    networks:
      - separated_network
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - docker/web/.env
    networks:
      - separated_network
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - separated_network

volumes:
  postgres_data:
  redis_data:

networks:
  separated_network:
