"""first_migration

Revision ID: 4981445a42ed
Revises: 
Create Date: 2022-05-12 12:34:27.889351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4981445a42ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', postgresql.UUID(), nullable=True, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_profile_id'), 'profiles', ['profile_id'], unique=True)
    op.create_table('rooms',
    sa.Column('id', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('room_type', Enum('PERSONAL', 'GROUP', name='roomchoice'), nullable=True)
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('message_type', Enum('TEXT', 'IMAGE', name='messagetype'), nullable=True),
    sa.Column('room_id', postgresql.UUID(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_updated'), 'messages', ['updated'], unique=False)
    op.create_table('rooms_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', postgresql.UUID(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'profile_id')
    )
    op.create_index(op.f('ix_rooms_profiles_id'), 'rooms_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_profiles_id'), table_name='rooms_profiles')
    op.drop_table('rooms_profiles')
    op.drop_index(op.f('ix_messages_updated'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_profiles_profile_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
